[project]
name = "faststream-compressors"
version = "1.0.0"
description = "A middleware for the FastStream framework to support message compression."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faststream[cli, nats]",
    "pre-commit>=4.0.1",
]

[project.optional-dependencies]
lz4 = [
    "lz4>=4.3.3",
]

[tool.uv.sources]
faststream = { git = "https://github.com/airtai/faststream", branch = "0.6.0"}

[dependency-groups]
lz4 = [
    "lz4>=4.3.3",
]
dev = [
    "pre-commit>=4.0.1",
]

[tool.ruff]
lint.select = ["E", "F", "W", "Q", "I", "B"]

lint.fixable = ["ALL"]
lint.unfixable = []

line-length = 89
